"""unhooked_date added

Revision ID: 592237888ae1
Revises: 853bf92f6173
Create Date: 2024-11-10 20:36:50.756799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592237888ae1'
down_revision = '853bf92f6173'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unhooked_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('unhooked_date')

    # ### end Alembic commands ###

