"""Last purchase date prod

Revision ID: 853bf92f6173
Revises: 97e3b2646b35
Create Date: 2024-09-15 12:23:40.159239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853bf92f6173'
down_revision = '97e3b2646b35'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_purchase_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_purchase_date')

    # ### end Alembic commands ###

