"""savings ledger schema: missing columns + sync_cursor

Revision ID: fa869c032f76
Revises: g0a1b2c3d4e5
Create Date: 2026-07-05 13:11:16.457745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa869c032f76'
down_revision = 'g0a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plaid_item_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plaid_institution_name', sa.String(length=200), nullable=True))

    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('savings_txn_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('savings_txn_id')
        batch_op.drop_column('savings_decision')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plaid_institution_name')
        batch_op.drop_column('plaid_item_id')
        batch_op.drop_column('plaid_access_token_enc')

    op.drop_table('sync_cursor')
    # ### end Alembic commands ###

