"""Description of changes

Revision ID: fc0b9df237ad
Revises: edc54aaf9eaf
Create Date: 2024-08-02 17:34:55.415655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0b9df237ad'
down_revision = 'edc54aaf9eaf'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=10000), nullable=True))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=10000), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###

