"""add sync cursor table

Revision ID: 0b034ba4aad4
Revises: 2227ca8684a9
Create Date: 2026-07-05 12:27:03.627856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b034ba4aad4'
down_revision = '2227ca8684a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # NOTE: drop_table('favorite_brand') removed by hand — legacy table with
    # no model; out of scope.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_cursor')
    # ### end Alembic commands ###
