"""add gmail connector and backfill fields

Revision ID: 1b09da4c74d0
Revises: b1c086fcaf58
Create Date: 2026-05-03 11:10:46.751845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b09da4c74d0'
down_revision = 'b1c086fcaf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_client_id', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('google_client_secret', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('gmail_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gmail_token_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('gmail_connected_email', sa.String(length=150), nullable=True))

    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backfilled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('source_email_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('source_email_id')
        batch_op.drop_column('backfilled')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gmail_connected_email')
        batch_op.drop_column('gmail_token_expiry')
        batch_op.drop_column('gmail_refresh_token')
        batch_op.drop_column('gmail_access_token')
        batch_op.drop_column('google_client_secret')
        batch_op.drop_column('google_client_id')

    # ### end Alembic commands ###
