"""add plaid connection to user

Revision ID: 2227ca8684a9
Revises: 3e1d0748f507
Create Date: 2026-07-05 12:16:06.889941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2227ca8684a9'
down_revision = '3e1d0748f507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: drop_table('favorite_brand') removed by hand (again) — legacy
    # table with no model; out of scope.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plaid_access_token_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plaid_item_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plaid_institution_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plaid_institution_name')
        batch_op.drop_column('plaid_item_id')
        batch_op.drop_column('plaid_access_token_enc')

    # ### end Alembic commands ###
