"""Description of changes

Revision ID: 2f61f2ec0d73
Revises: d166199c7ead
Create Date: 2024-07-25 13:28:56.804394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f61f2ec0d73'
down_revision = 'd166199c7ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(precision=100.0), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
