"""Description of changes

Revision ID: 3c60a5a313a4
Revises: eb84e533f874
Create Date: 2024-07-27 16:21:22.402815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c60a5a313a4'
down_revision = 'eb84e533f874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.alter_column('wish_period',
               existing_type=sa.TIMESTAMP(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.alter_column('wish_period',
               existing_type=sa.NUMERIC(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###
