"""add savings decision to wish_item

Revision ID: 3e1d0748f507
Revises: 64e57048e759
Create Date: 2026-07-05 11:50:49.073290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1d0748f507'
down_revision = '64e57048e759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: drop_table('favorite_brand') removed by hand again — legacy table
    # with no model; out of scope. (Autogenerate re-proposes it every time.)
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('savings_txn_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('savings_txn_id')
        batch_op.drop_column('savings_decision')

    # ### end Alembic commands ###
