"""Description of changes

Revision ID: 5da603fda8cc
Revises: 3c60a5a313a4
Create Date: 2024-07-27 16:23:17.828731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da603fda8cc'
down_revision = '3c60a5a313a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.alter_column('wish_period',
               existing_type=sa.NUMERIC(),
               type_=sa.Interval(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.alter_column('wish_period',
               existing_type=sa.Interval(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    # ### end Alembic commands ###
