"""add ledger core tables

Revision ID: 64e57048e759
Revises: 3b5c7e1d2a8f
Create Date: 2026-07-02 18:42:59.664019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64e57048e759'
down_revision = '3b5c7e1d2a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_account_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', name='uq_ledger_account_user_kind')
    )
    op.create_table('ledger_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wishitem_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.Column('provider_transfer_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wishitem_id'], ['wish_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_account.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate also proposed drop_table('favorite_brand') — a legacy
    # table with no model. Removed by hand: dropping it is out of scope for
    # this migration and would delete data.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger_entry')
    op.drop_table('ledger_transaction')
    op.drop_table('ledger_account')
    # ### end Alembic commands ###
