"""Description of changes

Revision ID: 6bb068cca439
Revises: c345578a0e96
Create Date: 2024-08-22 23:29:27.643909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb068cca439'
down_revision = 'c345578a0e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorited', sa.Boolean(), nullable=True))
        batch_op.drop_column('wish_to_purchase_period')
        batch_op.drop_column('wish_to_unhook_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wish_to_unhook_period', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('wish_to_purchase_period', sa.DATETIME(), nullable=True))
        batch_op.drop_column('favorited')

    # ### end Alembic commands ###
