"""User report start and end window added to User

Revision ID: 95707f49485c
Revises: fe9316dbb146
Create Date: 2025-01-01 17:34:30.069748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95707f49485c'
down_revision = 'fe9316dbb146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('report_end', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('initial_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('report_end')
        batch_op.drop_column('report_start')

    # ### end Alembic commands ###
