"""Add image_url to wishitem

Revision ID: add_image_url_to_wishitem
Revises: fe9316dbb146
Create Date: 2025-08-08 21:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_image_url_to_wishitem'
down_revision = 'fe9316dbb146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=10000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
