"""Description of changes

Revision ID: eb84e533f874
Revises: 2f61f2ec0d73
Create Date: 2024-07-27 16:09:20.323451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb84e533f874'
down_revision = '2f61f2ec0d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wish_period', sa.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('wish_period')

    # ### end Alembic commands ###
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish_item', sa.Column('favorited', sa.Boolean(), nullable=True))
    op.execute('UPDATE wish_item SET favorited = False WHERE favorited IS NULL')
    op.alter_column('wish_item', 'favorited', nullable=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish_item', 'favorited')
    # ### end Alembic commands ###