"""Initial date of wishitem added

Revision ID: fe9316dbb146
Revises: 1e06c6a8a47a
Create Date: 2024-12-31 00:17:07.857407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9316dbb146'
down_revision = '1e06c6a8a47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('unhooked_date', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wish_item', schema=None) as batch_op:
        batch_op.drop_column('unhooked_date')
        batch_op.drop_column('initial_date')

    # ### end Alembic commands ###
